version: '3'

services:
  test:
    container_name: test
    build: 
      context: .
      dockerfile: ./dockerfile-test
  main:
    container_name: main
    build: 
      context: .
      dockerfile: ./dockerfile
    ports: 
      - 8080:8080
